#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'rbenv', :github => 'fnichol/chef-rbenv', :ref => 'v0.7.2'
cookbook 'ruby_build'
cookbook 'postgresql', :github => 'phlipper/chef-postgresql'
cookbook 'locale', :github => 'deepak/chef-locale', :ref => 'deepak/bugfix/set-language'
cookbook 'git'
