setup: &setup
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: vagrant
  password: vagrant

development:
  <<: *setup
  database: blog_development

test:
  <<: *setup
  database: blog_test
